shop/config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  get '/carrinho' => 'carrinho#index'
  get '/carrinho/limpar' => 'carrinho#limparCarrinho'
  get '/carrinho/:id' => 'carrinho#add'

  resources :produtos
  root 'jogos#home'

  get 'jogos/sobre'

  get 'jogos/perguntas'

  get 'jogos/contato'

end

shop/app/models/produto.rb
class Produto < ActiveRecord::Base
end

shop/app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

shop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

shop/app/controllers/carrinho_controller.rb
class CarrinhoController < ApplicationController
  def add 
  	id = params[:id]
  		if session[:carrinho] then
  			carrinho = session[:carrinho]
  		else
  			session[:carrinho] = {}
  			carrinho = session[:carrinho]
  		end
  		
  		if carrinho[id] then
  			carrinho[id] = carrinho[id] + 1
  		else
  			carrinho[id] = 1
  		end
  	redirect_to :action => :index
  end
  
  def limparCarrinho
  		session[:carrinho] = nil
  		redirect_to :action => :index
  end
						
  def index
  	if session[:carrinho] then
  		@carrinho = session[:carrinho]
  	else		
  		@carrinho = {}
  	end
  end

end

shop/app/controllers/jogos_controller.rb
class JogosController < ApplicationController
  def home
  end

  def sobre
  end

  def perguntas
  end

  def contato
  end
end

shop/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto foi deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:titulo, :descricao, :imagem_url, :valor, :categoria, :subcategoria)
    end
end

shop/app/helpers/application_helper.rb
module ApplicationHelper
end

shop/app/helpers/carrinho_helper.rb
module CarrinhoHelper
end

shop/app/helpers/jogos_helper.rb
module JogosHelper
end

shop/app/helpers/produtos_helper.rb
module ProdutosHelper
end

shop/app/views/carrinho/index.html.erb
<h1>Seu Carrinho</h1>
<%= link_to 'Limpar carrinho', carrinho_limpar_path %>
<br><br><br>

<% total = 0 %>

<ul>
<% @carrinho.each do | id, quantity | %>
	<% produto = Produto.find_by_id(id) %>

	<li>	
		<%= link_to produto.titulo, produto %> 
		<p><%= produto.descricao %></p>
		<p><%= number_to_currency(produto.valor, :unit => 'R$') %><p>
		<p>Quantidade: <%= quantity %></p>	
	</li>
	<% total += quantity * produto.valor %>
<% end %>
<br>

<p><b><%= number_to_currency(total, :unit => 'R$') %></b></p>
</ul>

shop/app/views/jogos/contato.html.erb
<h1>Jogos#contato</h1>
<p>Find me in app/views/jogos/contato.html.erb</p>

shop/app/views/jogos/home.html.erb
<h1>Jogos#home</h1>
<p>Find me in app/views/jogos/home.html.erb</p>

shop/app/views/jogos/perguntas.html.erb
<h1>Jogos#perguntas</h1>
<p>Find me in app/views/jogos/perguntas.html.erb</p>

shop/app/views/jogos/sobre.html.erb
<h1>Jogos#sobre</h1>
<p>Find me in app/views/jogos/sobre.html.erb</p>

shop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
	<div id="jogos_nav">
		<%= link_to "Home", root_path %>
		<%= link_to "Produtos", produtos_path %>
		<%= link_to "Sobre", jogos_sobre_path %>
		<%= link_to "Perguntas", jogos_perguntas_path %>
		<%= link_to "Contato", jogos_contato_path %>
	</div>
	
	<div id="entrar">	
		<% if usuario_signed_in? %>	
			<%= link_to "Sair", destroy_usuario_session_path, method: :delete %>
		<% else %>	
			<%= link_to "Entrar", new_usuario_session_path %>
			<%= link_to "Cadastrar", new_usuario_registration_path %>
		<% end %>
	</div>
</nav>
	
<div id="main_wrap">	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<%= yield %>
</div>
</body>
</html>

shop/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :imagem_url %><br>
    <%= f.text_field :imagem_url %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :subcategoria %><br>
    <%= f.text_field :subcategoria %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

shop/app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

shop/app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Imagem_url</th>
      <th>Valor</th>
      <th>Categoria</th>
      <th>Subcategoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.titulo %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.imagem_url %></td>
        <td><%= produto.valor %></td>
        <td><%= produto.categoria %></td>
        <td><%= produto.subcategoria %></td>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Excluir', produto, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        <td><a href="/carrinho/<%= produto.id %>" > Adicionar ao Carrinho</a></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %>

shop/app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

shop/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Sobre o produto</h1>
<br><br>
<p>
  <strong>Titulo:</strong>
  <%= @produto.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Imagem url:</strong>
  <%= @produto.imagem_url %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @produto.valor %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @produto.categoria %>
</p>

<p>
  <strong>Subcategoria:</strong>
  <%= @produto.subcategoria %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>